#!/usr/bin/env perl
use strict;
use warnings;

use Data::Dumper::Compact qw(ddc);
use File::Basename;
use HTML::D3;
use Lingua::EN::Fathom;
use File::Find::Rule;

my $path = shift || die "Usage: perl $0 /path/to/files";

my @files = File::Find::Rule->file()->name('*.txt')->in($path);

my $text = Lingua::EN::Fathom->new();

# print "Chars\tWords\tComplex\tSentences\tSylW\tWpS\tFOG\tFlesch\tKincaid\tName\n";

my %data;

for my $file (sort @files) {
    $text->analyse_file($file);

    my $basename = basename($file, qw(.txt));

    # printf "%d\t%d\t%.2f\t%d\t%.2f\t%.2f\t%.2f\t%.2f\t%.2f\t%s\n",
    # push $data{num_chars}->@*,             { label => $basename, value => $text->num_chars };
    # push $data{num_words}->@*,             { label => $basename, value => $text->num_words };
    # push $data{percent_complex_words}->@*, { label => $basename, value => $text->percent_complex_words * 100 };
    # push $data{num_sentences}->@*,         { label => $basename, value => $text->num_sentences };
    # push $data{syllables_per_word}->@*,    { label => $basename, value => $text->syllables_per_word };
    push $data{words_per_sentence}->@*,    { label => $basename, value => $text->words_per_sentence };
    push $data{fog}->@*,                   { label => $basename, value => $text->fog };
    # push $data{flesch}->@*,                { label => $basename, value => $text->flesch };
    # push $data{kincaid}->@*,               { label => $basename, value => $text->kincaid };
}
# print ddc \%data;

my $chart = HTML::D3->new(
    width  => 1000,
    height => 800,
    title  => 'Inaugural Address Trends',
);

my @data;
for my $key (keys %data) {
    push @data, { name => $key, data => $data{$key} };
}

print $chart->render_multi_series_line_chart_with_tooltips(\@data);
