#!/usr/bin/env perl
use strict;
use warnings;

use Data::Dumper::Compact qw(ddc);
use File::Basename;
use HTML::D3;
use Lingua::EN::Fathom;
use File::Find::Rule;

my $path = shift || die "Usage: perl $0 /path/to/files";

my @files = File::Find::Rule->file()->name('*.txt')->in($path);

my $text = Lingua::EN::Fathom->new();

# print "Chars\tWords\tComplex\tSentences\tSylW\tWpS\tFOG\tFlesch\tKincaid\tName\n";

my %data;

for my $file (sort @files) {
    $text->analyse_file($file);

    my $basename = basename($file, qw(.txt));

    # printf "%d\t%d\t%.2f\t%d\t%.2f\t%.2f\t%.2f\t%.2f\t%.2f\t%s\n",
    push $data{chars}->@*, { label => '', value => $text->num_chars };
    push $data{words}->@*, { label => '', value => $text->num_words };
    push $data{complex}->@*, { label => '', value => $text->percent_complex_words };
    push $data{sentences}->@*, { label => '', value => $text->num_sentences };
    push $data{syll_per_word}->@*, { label => '', value => $text->syllables_per_word };
    push $data{word_perl_sent}->@*, { label => '', value => $text->words_per_sentence };
    push $data{fog}->@*, { label => '', value => $text->fog };
    push $data{flesch}->@*, { label => '', value => $text->flesch };
    push $data{kincaid}->@*, { label => '', value => $text->kincaid };
    push $data{name}->@*, { label => '', value => $basename };
}
# print ddc \%data;

__END__
my $chart = HTML::D3->new(
    width  => 800,
    height => 600,
    title  => 'Inaugural Address Trends',
);
