#!/usr/bin/env perl
use strict;
use warnings;

use File::Slurp::Tiny qw( read_file );
use Text::Ngrams;
use Lingua::StopWords qw( getStopWords );

# Get our cmmand line arguments
my $filename = shift || die "Usage: perl $0 file.txt\n";
my $n        = shift || 2;

# Read-in the file content
my $content = read_file($filename);

# Normalize the content to all lowercase
$content = lc $content;

# Remove integers
$content =~ s/\b\d+\b//gs;

# Remove stopwords
for my $sw ( keys %{ getStopWords('en') } ) {
    $content =~ s/\b$sw\b//gs;
}

# Process the content into ngrams
my $ngram = Text::Ngrams->new(
    type       => 'word',
    windowsize => $n,
);
$ngram->process_text($content);
$ngram->to_string(
    onlyfirst => 1000,
    out       => "$0.profile",
    spartan   => 1,
    orderby   => 'frequency',
#    normalize => 1,
);
