#!/usr/bin/env perl
use strict;
use warnings;

use File::Slurp::Tiny qw( read_file );
use Text::Ngrams;
use Lingua::StopWords qw( getStopWords );

my $filename = shift || die "Usage: perl $0 file.txt\n";
my $n        = shift || 2;
my $content  = read_file($filename);

$content = lc $content;

$content =~ s/\b\d+\b//gs;

for my $sw ( keys %{ getStopWords('en') } ) {
#warn "S:$sw\n";
    $content =~ s/\b$sw\b//gs;
}
#warn "C:$content\n";

my $ngram = Text::Ngrams->new(
    type       => 'word',
    windowsize => $n,
);
$ngram->process_text($content);
$ngram->to_string(
    onlyfirst => 1000,
    out       => "$0.profile",
    spartan   => 1,
    orderby   => 'frequency',
#    normalize => 1,
);
