#!/usr/bin/env perl
use strict;
use warnings;

use WordNet::QueryData;
$ENV{WNHOME} = '/usr/local/Cellar/wordnet/3.1/dict/';
my $wn = WordNet::QueryData->new(
    noload => 1,
    dir    => $ENV{WNHOME},
);

my $word  = shift || 'small';
my $sense = shift || 'a';

$word .= "#$sense#1";

my @syns = $wn->querySense( $word, 'syns' );
my @ants = $wn->queryWord( $word, 'ants' );
my @hype = $wn->querySense( $word, 'hypes' );
my @hypo = $wn->querySense( $word, 'hypos' );
my @mero = $wn->querySense( $word, 'mero' );
my @holo = $wn->querySense( $word, 'holo' );
my @sim  = $wn->querySense( $word, 'sim' );
my @enta = $wn->querySense( $word, 'enta' );
my @caus = $wn->querySense( $word, 'caus' );

print 'Synsets: ', join( ', ', @syns ), "\n";
print 'Antonyms: ', join( ', ', @ants ), "\n";
print 'Hypernyms: ', join( ', ', @hype ), "\n";
print 'Hyponyms: ', join( ', ', @hypo ), "\n";
print 'Meronyms: ', join( ', ', @mero ), "\n";
print 'Holonyms: ', join( ', ', @holo ), "\n";
print 'Similar to: ', join( ', ', @sim ), "\n"; # if $sense eq 'a';
print 'Entailment: ', join( ', ', @enta ), "\n"; # if $sense eq 'v';
print 'Cause: ', join( ', ', @caus ), "\n"; # if $sense eq 'v';
