#!/usr/bin/env perl
use strict;
use warnings;

use File::Find::Rule;
use File::Slurper qw( read_text write_text );
use Text::Unidecode;

my $dir = shift || die "Usage: perl $0 /some/directory";
my $ext = shift || 'txt';

my @files = File::Find::Rule->file()->name( '*.' . $ext )->in($dir);

for my $file ( @files ) {
    warn "File: $file\n";
    my $content;
    eval { $content = read_text($file) };
    if ( $@ ) {
        warn $@;
        next;
    }
    $content = unidecode($content);
    write_text( $file, $content );
}
