#!/usr/bin/env perl
use strict;
use warnings;

# Easy wordle cheating

use IO::Prompt::Tiny qw(prompt);
use List::Util qw(all);

my $words = '/usr/share/dict/words';
my $n = 5;
my $regex = '';
my $unknown = join '', 'a' .. 'z';
my $in_word = '';

for my $i (1 .. $n) {
    my $choice = prompt("What is letter $i, if known?");
    my $part;
    if ($choice) {
        $part = $choice;
    }
    else {
        $choice = prompt('Are there any in-word letters known?');
        $in_word .= $choice;

        $choice = prompt('Are there any not-in-word letters known?');
        for my $letter (split //, $choice) {
            $unknown =~ s/$letter//;
        }
        $part = $unknown;
    }
    $regex .= "[$part]";
    print "Growing regex: $regex\n";
}

my @in_word = split //, $in_word;

$regex = "'^$regex\$'";
print "Regex: $regex\n";

my $possibles = qx{ grep $regex $words };

my $i = 0;
for my $word (split /\n/, $possibles) {
    next if $word =~ /'/;
    next unless all { $word =~ /$_/ } @in_word;
    $i++;
    print "\t$i. $word\n";
}
